name: Build and Deploy Ren'Py Game

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y bzip2 libsdl2-2.0-0 libsdl2-image-2.0-0 libsdl2-mixer-2.0-0 libsdl2-ttf-2.0-0

    - name: Install Pygame
      run: |
        wget https://www.renpy.org/dl/8.2.1/renpy-8.2.1-sdk.tar.bz2
        python -m pip install --upgrade pip
        python -m pip install pygame
        tar -jxvf renpy-8.2.1-sdk.tar.bz2


    - name: Install RenPy
      uses: PaxlavaGames/renpy-install@main
      with:
        version: "8.2.0"
        download_web: "yes"


    - name: Run unit tests
      run: |
          python soundgame/game/utest.py

    - name: Build RenPy
      uses: PaxlavaGames/renpy-web-build@main
      with:
        path: "./soundgame"



    # - name: Build Game
    #   run: |
    #     echo "Starting Ren'Py build"
    #     mkdir output_build
    #     sudo chmod -R 777 .
    #     cd renpy-8.2.1-sdk/
        
    #     sudo chmod -R 777 output_build
    #     sudo ./renpy.sh launcher web_build ../soundgame/ --destination ../output_build
    #   continue-on-error: true



    - name: Install Butler
      run: |
        curl -L -o butler.zip https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default
        unzip butler.zip
        chmod +x butler

    - name: Deploy to itch.io
      run: |
        ./butler push web_build.zip dnzsnkrbck/ninjahamster:html
      env:
        BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}


